# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd508b936bf6c0273ba36f583345df29b3bdd84942a77ae9a9b8fe5907bbb3ba471d45bf7bc32c0802b2c889a5a6ec924081046ec00b668bbc82bbc3bee9a984

test:
  secret_key_base: 0d01e152f714c3960309fb6a102b36881e90bb575c91334590ab25824a47380d1992c13d05188850f44c9e7c4322df51f98eaa4da118b675e08aaa9bd4f95b2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
